name: "CI"

on:
  push:
    branches:
      - main
  pull_request: { }

jobs:
  publish:
    name: Pages
    runs-on: ubuntu-latest
    container: marcusgrass/pages-check:latest
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: trunk build --release
      - name: Publish
        run: git push origin `git subtree split --prefix dist main`:gh-pages --force