name: "CI"

on:
  push:
    branches:
      - main
  pull_request: { }

jobs:
  publish:
    name: Pages
    runs-on: ubuntu-latest
    container: marcusgrass/pages-check:latest
    steps:
      - uses: actions/checkout@v3
      - name: Publish
        run: bash ${GITHUB_WORKSPACE}/.github/publish-pages.sh